class AddColsToPointsofinterests < ActiveRecord::Migration[4.2]
  def change
    add_column :pointsofinterests, :poi_info_id, :integer
	add_column :pointsofinterests, :point_type, :string
  	add_column :pointsofinterests, :public_access, :string
  	add_column :pointsofinterests, :latitude, :decimal
  	add_column :pointsofinterests, :longitude, :decimal
  	add_column :pointsofinterests, :web_poi, :string
  	add_column :pointsofinterests, :web_street_addr, :string
  	add_column :pointsofinterests, :web_muni_addr, :string
  	add_column :pointsofinterests, :parking_connection_id, :integer
  	add_column :pointsofinterests, :parking_info_id, :integer
  	add_column :pointsofinterests, :alt_name, :string
  	add_column :pointsofinterests, :alt2_name, :string
  	add_column :pointsofinterests, :name, :string
  	add_column :pointsofinterests, :ada, :integer
  	add_column :pointsofinterests, :bike_parking, :integer
  	add_column :pointsofinterests, :bike_rental, :integer
  	add_column :pointsofinterests, :birding, :integer
  	add_column :pointsofinterests, :boat_ramp, :integer
  	add_column :pointsofinterests, :boat_rental, :integer
  	add_column :pointsofinterests, :camping, :integer
  	add_column :pointsofinterests, :canoe, :integer
  	add_column :pointsofinterests, :comfortstation, :integer
  	add_column :pointsofinterests, :cross_country, :integer
  	add_column :pointsofinterests, :cycling, :integer
  	add_column :pointsofinterests, :disc_golf, :integer
  	add_column :pointsofinterests, :dog_friendly, :integer
  	add_column :pointsofinterests, :dog_leash, :integer
  	add_column :pointsofinterests, :drinkingwater, :integer
  	add_column :pointsofinterests, :drone, :integer
  	add_column :pointsofinterests, :ecological, :integer
  	add_column :pointsofinterests, :equestrian, :integer
  	add_column :pointsofinterests, :fishing, :integer
  	add_column :pointsofinterests, :ice_fishing, :integer
  	add_column :pointsofinterests, :gas_powered, :integer
  	add_column :pointsofinterests, :golf, :integer
  	add_column :pointsofinterests, :hiking, :integer
  	add_column :pointsofinterests, :indoor_rental, :integer
  	add_column :pointsofinterests, :large_capacity, :integer
  	add_column :pointsofinterests, :m_airplane, :integer
  	add_column :pointsofinterests, :m_boat, :integer
  	add_column :pointsofinterests, :nature_center, :integer
  	add_column :pointsofinterests, :natureplay, :integer
  	add_column :pointsofinterests, :no_alcohol, :integer
  	add_column :pointsofinterests, :no_parking, :integer
  	add_column :pointsofinterests, :overlook, :integer
  	add_column :pointsofinterests, :public_building, :integer
  	add_column :pointsofinterests, :picnic_grove, :integer
  	add_column :pointsofinterests, :shelter, :integer
  	add_column :pointsofinterests, :skating_ice, :integer
  	add_column :pointsofinterests, :skating_inline, :integer
  	add_column :pointsofinterests, :sledding, :integer
  	add_column :pointsofinterests, :snowmobile, :integer
  	add_column :pointsofinterests, :swimming, :integer
  	add_column :pointsofinterests, :toboggan, :integer
  	add_column :pointsofinterests, :volunteer, :integer
  	add_column :pointsofinterests, :zip_line, :integer
  	add_column :pointsofinterests, :nature_preserve, :integer
  	add_column :pointsofinterests, :no_fishing, :integer
  	add_column :pointsofinterests, :driving_range, :integer
  end
end
